.TH nvram_export 1 "Sep 07, 2006"
.SH NAME
nvram_export \- Cisco 7200 NVRAM configuration export
.SH SYNOPSIS
.B nvram_export
.I nvram_file
.I config_file
.br
.SH DESCRIPTION
export configuration from dynamips nvram file.
.SH REPORTING BUGS
.br
Please send bug reports to http://www.ipflow.utc.fr/bts/
.SH SEE ALSO
.br
\fBdynmips\fP(1), \fBhypervisor_mode\fP(7)
.br
.UR
http://www.ipflow.utc.fr/index.php/
.UE
.br
.UR
http://www.ipflow.utc.fr/blog/
.UE
.br
.UR
http://hacki.at/7200emu/index.php
.UE
.fBdynamips\fP(1)
.SH AUTHOR
\fBdynamips\fP was written by Fabien Devaux, Christophe Fillot (cf@utc.fr)
and MtvE. This manual page was written by Erik Wenzel <erik@debian.org>
for the Debian GNU/Linux system (but may be used by others).

